import Head from 'next/head'
import { Navbar } from '../components/Navbar'
import { NavItem } from '../components/NavItem'
import InstagramIcon from '@material-ui/icons/Instagram';
import FacebookIcon from '@material-ui/icons/Facebook';
import ExpandMoreIcon from '@material-ui/icons/ExpandMore';
import { DropdownMenu } from '../components/DropdownMenu';
import { Hero } from '../components/Hero';
import { About } from '../components/About';
import { Contact } from '../components/Contact';
import { Resume } from '../components/Resume';
import { Portfolio } from '../components/Portfolio';
import Brightness4Icon from '@material-ui/icons/Brightness4';
import { Switch } from '@material-ui/core';
import { useEffect, useState } from 'react';
import EmailIcon from '@material-ui/icons/Email';


export default function Home() {
  const [theme,setTheme] = useState('dark-theme');
  const [checked,setChecked] = useState(false);

  useEffect(() =>{
    document.documentElement.className = theme;
  }, [theme])

  const themeToggler = () => {
    if(theme === 'light-theme'){
      setTheme('dark-theme');
      setChecked(false)
    }else {
      setTheme('light-theme')
      setChecked(true)
    }
  }

  useEffect (() =>{
    let a = document.getElementsByClassName('Home_iconBtn__1XyI6')
    a[3].addEventListener('click', (e) => {
      e.preventDefault();
      e.target.classList.toggle('rotate')
    })
  }, [])


  return (
    <div className="Bodywrap">
      <Head>
        <title>Portfolio Website!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>   
      <Navbar>
        <NavItem icon={<InstagramIcon />} link='http://instagram.com/bojan_martinov' />
        <NavItem icon={<FacebookIcon />} link='http://facebook.com/b.martinov96'/>
        <NavItem icon={<EmailIcon />} link='mailto: bojanforgaming@hotmail.com'/>
        <NavItem icon={<ExpandMoreIcon/>} >
          <DropdownMenu />
        </NavItem>
      </Navbar>
      <div className="light-dark-mode">
        <div className="left-content">
          <Brightness4Icon />
        </div>
        <div className="right-content">
          <Switch 
            value = ""
            checked = {checked}
            inputProps= {{'aria-label': ''}}
            size="medium"
            onClick={themeToggler}
          />
        </div>
      </div>

      <Hero />
      <About />
      <Resume />
      <Portfolio />
      <Contact />
    </div>
  )
}
